### ISSUE TITLE
[Bug] A bug from here: https://stake.reef.finance/baskets/custom-basket

### ISSUE THREAD

**Issue by 109km** [reef-defi/reef-chain#15]
When I move the composition's bars, the **HISTORIC SIMULATED PERFORMANCE** chart's data will be automatically switched to **last month**. But the duration option still displays what I chose before.

**Comment by jbargu** [comment]
This belongs to the [reef-client](https://github.com/reef-defi/reef-client/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repo, please open the issue there @109km.
