### ISSUE TITLE
How can I get some reef on my testnet account ?

### ISSUE THREAD

**Issue by vladislavzorin** [reef-defi/reef-chain#31]
I want a deploy contract, but I need a bit of reef for that

Reef testnet: 5H9ScUBbVdM1JT27NQXH1dGRH4Hyp7bdfNi4EqNsX6Ti41Dm

**Comment by mwarzynski** [comment]
@vladislavzorin https://docs.reef.finance/docs/developers/quick-start/#deploy-on-testnet
