### ISSUE TITLE
integrate substrate-api-sidecar

### ISSUE THREAD

**Issue by vae520283995** [reef-defi/reef-chain#33]
Hello, developers, do you have any plans to integrate reef into https://github.com/paritytech/substrate-api-sidecar? At present, exchanges are all tokens that integrate the substrate chain through substrate-api-sidecar

**Comment by Netherdrake** [comment]
Thanks for the suggestion, we will look into it

**Comment by frisitano** [comment]
This can probably be closed now @Netherdrake

**Comment by jbargu** [comment]
Download `types.json`, `typesBundle.json` from https://github.com/reef-defi/reef.js/tree/master/packages/type-definitions/src/json and then specify them in `.env` file for your sidecar instance as:
```
SAS_SUBSTRATE_TYPES_BUNDLE=<path>/typesBundle.json
SAS_SUBSTRATE_TYPES=<path>/types.json
```
and it will already work for you.
