### ISSUE TITLE
Issue with mainnet

### ISSUE THREAD

**Issue by 4skinSkywalker** [reef-defi/reef-chain#51]
Hi guys,

I'm having problem with connecting to the mainnet, I get this error:
```
Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (76 bytes)
```

Edit: Want to tell you that I'm already paired with Reefs at hand...

If you wanna see it live: [https://www.ethbox.org/app/](https://www.ethbox.org/app/).

I can connect to the testnet no problem with the same code.
What's the problem? What to do?

Thanks,
Fredo

**Comment by Netherdrake** [comment]
You need to upgrade the JS libraries for v8.

`@reef-defi/evm-provider` needs to be updated to 1.0.3. You have to refresh yarn and make sure it uses the 1.0.3.
