### ISSUE TITLE
Test accounts does not have funds - Local node

### ISSUE THREAD

**Issue by NanezX** [reef-defi/reef-chain#59]
Hi everyone,

I ran a Reef local node and I get the test accounts correctly, but they has not fund to interact/deploy contracts. [Here](https://docs.reef.io/docs/developers/accounts/?#developer-accounts), the documentation said:

> ...dummy accounts (alice, bob, charlie…) that are pre-funded with REEF...

But I'm not able to see what I'm doing wrong. 

Aso, I added the `bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice` to hardhat.config to get the alice account as "Deployer". This is to have just one script to deploy to reef local, testnet and mainnet with "deployer" name. This is not the error because I tried without and the account does not have funds (in any case, the address and strateAddress are the same in both cases).

How I can get this work? Would be awesome deploy locally. I need to deploy a lot of contracts many times to test a few scenarios and I cant wait every day to get Reef to testnet. As you an understand, contract deployment have significally more cost that interact, so local node will be good. 

Thanks :)

**Comment by frisitano** [comment]
Please see the hardhat examples repo - https://github.com/reef-defi/hardhat-reef-examples.
You can access test accounts using: `const signer = await reef.getSignerByName("alice");` https://github.com/reef-defi/hardhat-reef-examples/blob/master/scripts/integration-test.js#L56

**Comment by NanezX** [comment]
Hey, I was not claiming the test accounts in local node. Since my accounts in testnet are already claimed, I really forgot about made this when start the node and use the test accounts.

Thanks :)
